version: '3'

# The default docker-compose.override file can use the "localhost" as the external name for testing web apps within the same dev machine. 
# The ESHOP_EXTERNAL_DNS_NAME_OR_IP environment variable is taken, by default, from the ".env" file defined like: 
#     ESHOP_EXTERNAL_DNS_NAME_OR_IP=localhost
# but values present in the environment vars at runtime will always override those defined inside the .env file
# An external IP or DNS name has to be used (instead localhost and the 10.0.75.1 IP) when testing the Web apps and the Xamarin apps from remote machines/devices using the same WiFi, for instance.

services:      
  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=${ESHOP_AZURE_REDIS:-basket.data}
      - identityUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105              #Local: You need to open your local dev-machine firewall at range 5100-5105.  at range 5100-5105. 
      - EventBusConnection=${ESHOP_AZURE_SERVICE_BUS:-rabbitmq}
    ports:
      - "5103:80"
    container_name: basket.api

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=sql.data;Database=Microsoft.eShopOnContainers.Services.CatalogDb;User Id=sa;Password=Pass@word
      - PicBaseUrl=http://${ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP}:5101/api/v1/pic/   #Local: You need to open your local dev-machine firewall at range 5100-5105.  at range 5100-5105.	  
      - EventBusConnection=${ESHOP_AZURE_SERVICE_BUS:-rabbitmq}
      - UseCustomizationData=False
      - AzureStorageEnabled=False
    ports:
      - "5101:80"
    container_name: catalog.api

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - SpaClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5104
      - XamarinCallback=http://${ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP}:5105/xamarincallback      #localhost do not work for UWP login, so we have to use "external" IP always
      - ConnectionStrings__DefaultConnection=Server=sql.data;Database=Microsoft.eShopOnContainers.Service.IdentityDb;User Id=sa;Password=Pass@word 
      - MvcClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5100              #Local: You need to open your local dev-machine firewall at range 5100-5105.  
      - UseCustomizationData=True
    ports:
      - "5105:80"

  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=sql.data;Database=Microsoft.eShopOnContainers.Services.OrderingDb;User Id=sa;Password=Pass@word
      - identityUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105             #Local: You need to open your local dev-machine firewall at range 5100-5105.  at range 5100-5105. 
      - EventBusConnection=${ESHOP_AZURE_SERVICE_BUS:-rabbitmq}
      - UseCustomizationData=True
    ports:
      - "5102:80"

  marketing.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=sql.data;Database=Microsoft.eShopOnContainers.Services.MarketingDb;User Id=sa;Password=Pass@word
      - MongoConnectionString=mongodb://nosql.data
      - MongoDatabase=MarketingDb
      - EventBusConnection=rabbitmq
      - ExternalCatalogBaseUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5101   #Local: You need to open your local dev-machine firewall at range 5100-5105.  at range 5100-5105.	  
      - identityUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105              #Local: You need to open your local dev-machine firewall at range 5100-5105.  at range 5100-5105. 
    ports:
      - "5110:80"

  webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - CatalogUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5101
      - OrderingUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5102
      - BasketUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5103
      - IdentityUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105
      - MarketingUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5110 #Local:  Use 10.0.75.1 in a "Docker for Windows" environment, if using "localhost" from browser. 
                                                 #Remote: Use ${ESHOP_EXTERNAL_DNS_NAME_OR_IP} if using external IP or DNS name from browser. 
      - UseCustomizationData=True
    ports:
      - "5100:80"

  sql.data:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    container_name: sql.data

  nosql.data:
    ports:
      - "27017:27017"
    container_name: nosql.data

  webstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - CatalogUrl=http://catalog.api/hc
      - OrderingUrl=http://ordering.api/hc
      - BasketUrl=http://basket.api/hc
      - IdentityUrl=http://identity.api/hc
      - mvc=http://webmvc/hc
      - spa=http://webspa/hc
    ports:
      - "5107:80"
    container_name: webstatus

  payment.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5108
      - EventBusConnection=rabbitmq
    ports:
      - "5108:80"

  locations.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=mongodb://nosql.data
      - Database=LocationsDb
      - identityUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105             #Local: You need to open your local dev-machine firewall at range 5100-5105.  at range 5100-5105. 
      - EventBusConnection=rabbitmq
    ports:
      - "5109:80"
